/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.crud.recursoshumanos;

/**
 *
 * @author neo
 */
public class DialogCliente extends javax.swing.JDialog {

    public DialogCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel10 = new javax.swing.JLabel();
        jButtonNovoRegistro2 = new javax.swing.JButton();
        jButtonGravar2 = new javax.swing.JButton();
        jButtonAlterar2 = new javax.swing.JButton();
        jButtonExcluir2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButtonPrimeiro2 = new javax.swing.JButton();
        jButtonAnterior2 = new javax.swing.JButton();
        jButtonProximo2 = new javax.swing.JButton();
        jButtonUltimo2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButtonSair2 = new javax.swing.JButton();
        jLabelPesquisa = new javax.swing.JLabel();
        jComboBoxPesquisa = new javax.swing.JComboBox<>();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	setTitle("Controle de Clientes");
	setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);

        jPanelMain2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain2.setPreferredSize(new java.awt.Dimension(1080, 692));
        jPanelMain2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar2.setBackground(new java.awt.Color(0, 51, 102));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel10.setText("      ");
        jToolBar2.add(jLabel10);

        jButtonNovoRegistro2.setText(" Novo Registro ");
        jButtonNovoRegistro2.setFocusable(false);
        jButtonNovoRegistro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovoRegistro2.setPreferredSize(new java.awt.Dimension(150, 23));
        jButtonNovoRegistro2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonNovoRegistro2);

        jButtonGravar2.setText(" Gravar ");
        jButtonGravar2.setFocusable(false);
        jButtonGravar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGravar2.setPreferredSize(new java.awt.Dimension(75, 24));
        jButtonGravar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonGravar2);

        jButtonAlterar2.setText(" Alterar ");
        jButtonAlterar2.setToolTipText("");
        jButtonAlterar2.setFocusable(false);
        jButtonAlterar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAlterar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonAlterar2);

        jButtonExcluir2.setText(" Excluir ");
        jButtonExcluir2.setFocusable(false);
        jButtonExcluir2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonExcluir2);
        jToolBar2.add(jSeparator5);

        jButtonPrimeiro2.setText(" Primeiro ");
        jButtonPrimeiro2.setFocusable(false);
        jButtonPrimeiro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeiro2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonPrimeiro2);

        jButtonAnterior2.setText(" Anterior ");
        jButtonAnterior2.setFocusable(false);
        jButtonAnterior2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonAnterior2);

        jButtonProximo2.setText(" Próximo ");
        jButtonProximo2.setFocusable(false);
        jButtonProximo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProximo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonProximo2);

        jButtonUltimo2.setText(" Último ");
        jButtonUltimo2.setFocusable(false);
        jButtonUltimo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonUltimo2);
        jToolBar2.add(jSeparator6);

        jButtonSair2.setText("   Sair   ");
        jButtonSair2.setFocusable(false);
        jButtonSair2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonSair2);

        jPanelMain2.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        jLabelPesquisa.setText("Pesquisar por");
        jPanelMain2.add(jLabelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));

        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome do Cliente", "Data de Nascimento", "CPF", "RG", "Endereço" }));
        jPanelMain2.add(jComboBoxPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, -1, -1));
        jPanelMain2.add(jTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 420, -1));

        jButtonPesquisar.setText("Pesquisar");
        jPanelMain2.add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 670, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atributos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 30, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome do Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RG:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 210, -1));

        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(65, 22));
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        jFormattedTextField3.setPreferredSize(new java.awt.Dimension(92, 22));
        jPanel1.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jPanelMain2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1040, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Data de Nascimento", "CPF", "RG", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanelMain2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 1040, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSair2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAlterar1;
    private javax.swing.JButton jButtonAlterar2;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAnterior1;
    private javax.swing.JButton jButtonAnterior2;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluir1;
    private javax.swing.JButton jButtonExcluir2;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonGravar1;
    private javax.swing.JButton jButtonGravar2;
    private javax.swing.JButton jButtonNovoRegistro;
    private javax.swing.JButton jButtonNovoRegistro1;
    private javax.swing.JButton jButtonNovoRegistro2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonPrimeiro1;
    private javax.swing.JButton jButtonPrimeiro2;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonProximo1;
    private javax.swing.JButton jButtonProximo2;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JButton jButtonSair2;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JButton jButtonUltimo1;
    private javax.swing.JButton jButtonUltimo2;
    private javax.swing.JComboBox<String> jComboBoxPesquisa;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMain1;
    private javax.swing.JPanel jPanelMain2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
