/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.crud.recursoshumanos;

import controller.CRUD;
import controller.enums.TipoAtributo;
import controller.db.Conexao;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neo
 */
public class DialogCliente extends javax.swing.JDialog {
    Conexao conexao;
    CRUD crud;

    public DialogCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        conexao = new Conexao();
        conexao.conectar();
        
        jTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        jTable.getColumnModel().getColumn(4).setPreferredWidth(20);
        jTable.getColumnModel().getColumn(5).setPreferredWidth(225);
        
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        
        crud = new CRUD(
                conexao,
                modelo,
                "cliente",
                new String[] {
                    "id_cliente",
                    "nome_cli",
                    "data_nasc",
                    "cpf",
                    "rg",
                    "endereco"
                },
                new TipoAtributo[] {
                    TipoAtributo.PK,
                    TipoAtributo.String,
                    TipoAtributo.String,
                    TipoAtributo.String,
                    TipoAtributo.String,
                    TipoAtributo.String
                },
                new JTextField[] {
                    jTextFieldID,
                    jTextFieldNome,
                    jFormattedTextFieldNasc,
                    jFormattedTextFieldCPF,
                    jFormattedTextFieldRG,
                    jTextFieldEndereco
                },
                jComboBoxPesquisa,
                jTextFieldPesquisa
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel10 = new javax.swing.JLabel();
        jButtonNovoRegistro2 = new javax.swing.JButton();
        jButtonGravar2 = new javax.swing.JButton();
        jButtonAlterar2 = new javax.swing.JButton();
        jButtonExcluir2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButtonPrimeiro2 = new javax.swing.JButton();
        jButtonAnterior2 = new javax.swing.JButton();
        jButtonProximo2 = new javax.swing.JButton();
        jButtonUltimo2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButtonSair2 = new javax.swing.JButton();
        jLabelPesquisa = new javax.swing.JLabel();
        jComboBoxPesquisa = new javax.swing.JComboBox<>();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jFormattedTextFieldNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelMain2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain2.setPreferredSize(new java.awt.Dimension(1080, 692));
        jPanelMain2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar2.setBackground(new java.awt.Color(0, 51, 102));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel10.setText("      ");
        jToolBar2.add(jLabel10);

        jButtonNovoRegistro2.setText(" Novo Registro ");
        jButtonNovoRegistro2.setFocusable(false);
        jButtonNovoRegistro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovoRegistro2.setPreferredSize(new java.awt.Dimension(150, 23));
        jButtonNovoRegistro2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNovoRegistro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoRegistro2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonNovoRegistro2);

        jButtonGravar2.setText(" Gravar ");
        jButtonGravar2.setFocusable(false);
        jButtonGravar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGravar2.setPreferredSize(new java.awt.Dimension(75, 24));
        jButtonGravar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGravar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonGravar2);

        jButtonAlterar2.setText(" Alterar ");
        jButtonAlterar2.setToolTipText("");
        jButtonAlterar2.setFocusable(false);
        jButtonAlterar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAlterar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterar2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonAlterar2);

        jButtonExcluir2.setText(" Excluir ");
        jButtonExcluir2.setFocusable(false);
        jButtonExcluir2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonExcluir2);
        jToolBar2.add(jSeparator5);

        jButtonPrimeiro2.setText(" Primeiro ");
        jButtonPrimeiro2.setFocusable(false);
        jButtonPrimeiro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeiro2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPrimeiro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiro2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonPrimeiro2);

        jButtonAnterior2.setText(" Anterior ");
        jButtonAnterior2.setFocusable(false);
        jButtonAnterior2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnterior2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonAnterior2);

        jButtonProximo2.setText(" Próximo ");
        jButtonProximo2.setFocusable(false);
        jButtonProximo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProximo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProximo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximo2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonProximo2);

        jButtonUltimo2.setText(" Último ");
        jButtonUltimo2.setFocusable(false);
        jButtonUltimo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUltimo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimo2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonUltimo2);
        jToolBar2.add(jSeparator6);

        jButtonSair2.setText("   Sair   ");
        jButtonSair2.setFocusable(false);
        jButtonSair2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonSair2);

        jPanelMain2.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        jLabelPesquisa.setText("Pesquisar por");
        jPanelMain2.add(jLabelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));

        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome do Cliente", "Data de Nascimento", "CPF", "RG", "Endereço" }));
        jPanelMain2.add(jComboBoxPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, -1, -1));
        jPanelMain2.add(jTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 420, -1));

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanelMain2.add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 670, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 390, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atributos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTextFieldID.setEnabled(false);
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome do Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 30));
        jPanel1.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 330, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RG:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel1.add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 330, -1));

        jFormattedTextFieldNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldNasc.setPreferredSize(new java.awt.Dimension(65, 22));
        jPanel1.add(jFormattedTextFieldNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 110, -1));

        jFormattedTextFieldRG.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel1.add(jFormattedTextFieldRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, -1));

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setPreferredSize(new java.awt.Dimension(92, 22));
        jPanel1.add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 110, -1));

        jPanelMain2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 850, 140));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Data de Nascimento", "CPF", "RG", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanelMain2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 1040, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSair2ActionPerformed

    private void jButtonNovoRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoRegistro2ActionPerformed
        crud.novoRegistro();
    }//GEN-LAST:event_jButtonNovoRegistro2ActionPerformed

    private void jButtonGravar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar2ActionPerformed
        crud.gravar();
    }//GEN-LAST:event_jButtonGravar2ActionPerformed

    private void jButtonAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterar2ActionPerformed
        crud.alterar();
    }//GEN-LAST:event_jButtonAlterar2ActionPerformed

    private void jButtonExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluir2ActionPerformed
        crud.excluir();
    }//GEN-LAST:event_jButtonExcluir2ActionPerformed

    private void jButtonPrimeiro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiro2ActionPerformed
        crud.primeiro();
    }//GEN-LAST:event_jButtonPrimeiro2ActionPerformed

    private void jButtonAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnterior2ActionPerformed
        crud.anterior();
    }//GEN-LAST:event_jButtonAnterior2ActionPerformed

    private void jButtonProximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximo2ActionPerformed
        crud.proximo();
    }//GEN-LAST:event_jButtonProximo2ActionPerformed

    private void jButtonUltimo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimo2ActionPerformed
        crud.ultimo();
    }//GEN-LAST:event_jButtonUltimo2ActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        crud.pesquisar();
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar2;
    private javax.swing.JButton jButtonAnterior2;
    private javax.swing.JButton jButtonExcluir2;
    private javax.swing.JButton jButtonGravar2;
    private javax.swing.JButton jButtonNovoRegistro2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro2;
    private javax.swing.JButton jButtonProximo2;
    private javax.swing.JButton jButtonSair2;
    private javax.swing.JButton jButtonUltimo2;
    private javax.swing.JComboBox<String> jComboBoxPesquisa;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMain2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
